### ISSUE TITLE
Add users

### ISSUE THREAD

**Issue by KLCrow** [DimaSamodurov/pet-adopt#11]
Реалізувати функціонали та тести по сценаріях:
1. login.feature
2. logout.feature
3. signup.feature
4. facebook_signup.feature

**Comment by KLCrow** [comment]
Зроблено. Весь функціонал по даному issue реалізований, всі тести-сценарії написані. Останній про логування через фейсбук, додав сьогодні. Після обєднання пулреквесту "Lyubomyr facebook signup.feature" можна закривати це issue.

**Comment by DimaSamodurov** [comment]
:+1:
